  query getAllVehicleModel($searchQuery:String) {
    getAllVehicleModel(searchQuery:$searchQuery) {
      totalCount
      nodes {
        _id    
        name
        modelYear
        generationID

      }
    }
  }